twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        #admin_name: '%env(ADMIN_NAME)%'
        name: 'LASQUELLEC Samuel'
        address: '4 place de la halle 18120 Massay'
        email: 'samuel.lasquellec@bbox.fr'
        company: 'LS Informatique'
        telephone: '07.84.44.13.71'
        siret: '83386478800025'
        ape: '9511Z'
        currency: 'euros'
        tva: 'non applicable ART.293B du CGI'
        quantity: '1'
        host: 'LWS'
        domain: 'test.fr'

when@test:
    twig:
        strict_variables: true
